name: "Auto Deployment"

on:
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    outputs:
      status: ${{job.status}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "✅ storybook: ${{steps.chromatic.outputs.storybookUrl}}"
